language: java

jdk:
  - oraclejdk9
  - oraclejdk10
  - openjdk10
  - openjdk11

matrix:
  fast_finish: true
  allow_failures:
    - jdk: openjdk11

cache:
  directories:
    - $HOME/.m2

env:
  global:
    secure: Ud4Dv+0AwQEZ718aco1UQUgzAgEiUz4xT5IvKccS63lJu9de4Sj9upXTkNs2u7T6CtFEe06mjGDYWmN1HdkL8FEdRkM2PeLMtJaMUvghd//x1XcIv8PWzHYADmejpP18quS9CvR3gfKbf6r5WxplauRrdr0vvsj2lR/dU3S0lkziNIQeFkp0rHpY9CuoHTApWM059F1xnUVh+QSWvh62fSDYaQeId5IBt/WA76GShDkOO0kZYHK90Lya6EOIfX620fqsH7S1PJKJrV1ABf7sL8FCmmsYrzM/6913igzsj5OVVQ//Li21cMFVSKobSGVNPkyWvOVi7MMU24jylet6i6SQjkDO36rl6CZvy2XmkLnUoaePH1X+4kZdmFcn4YPx/cW0CS2eQnt5+0C02mUszjXaGSU6/qWnpDOvcffuGlPj22eVm//oRlsyzQEwIiV/4ULpG5/y++WLhudM6eKFJLbuOG7MKuqWEMz8iPKhuBQE1DkqOpBrsKYKu4Idc7CxhC5jTu+0+vLpueaFaCKJQ+aCVFSq/SU7oTwqYWQTDGgpnvYTz/eYKr8bKww+Im9YUB2ey6A5q7c9S2H9s0MO5sMX/U4ABtq6NgxEZbr9iqfETy633QTzLcWxonrWgbrcldkHmoWikhF6pgpu42S8IgkuC46yLDDr+Chu6WnHpOI=

install: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P travis

script: mvn verify -B -P travis

after_success:
  - mvn jacoco:report coveralls:report -P travis
